library(MASS)

data = read.csv("bank_data.csv")

## Calcular el Modelo

data$y= as.factor(data$y)

## CALCULAR EL MODELO 

reglog = glm(data$y~duration, data = data, family = binomial)

##log(p/1-p) = b0 + b1 x1 + ... 
summary(reglog)
## PARECE QUE LA DURACIÓN ES SIGNIFICATIVA YA QUE APORTA PODER EXPLICATIVO
## PARA PODER PREDECIR SI EL EL INDIVIDIO SE VA A SUSCRIBIR AL DEPÓSITO
## A PLAZO

## CALCULAR EL ODDS RATIO 
exp(reglog$coefficients)
## ES DECIR POR CADA UNIDAD QUE AUMENTA LA VARIABLE DURATION, EL ODDS DE 
## QUE SE PRESENTE EL EVENTE AUMENTA UN 1,003



## VER PROBABILIDADES 
## CALCULAMOS LAS PROBABILIDADES PARA TENER LOS VALORES CALCULADOS O AJUSTADOS
reglog$fitted.values

## ELEGIMOS PUNTO DE CORTE PARA LA PROBABILIDAD

data_predicho <- (reglog$fitted.values>0.5)

#########################################
## ¿CÓMO DE EFECTIVO ES ESTE MODELO?
## LO VEMOS CON LA MATRIZ DE CORRELACION: HAY QUE TENER EN CUENTA QUE 
## LOS VERDADEROS POSITIVOS Y NEGATIVOS SE MAXIMICEN (DIAGONALES) Y 
## QUE LOS FALSOS POSITIVOS: PREDECIR VERDADERO ALGO QUE ERA FALSO
## FALSOS NEGATIVOS: PREDECIR FALSO ALGO QUE ES VERDADERO;
## NO SEAN MENORES VIEDO EL PORCENTAJE EN ACCURACY, SENSIBILIDAD Y ESPECIFICIDAD (INDICADORES DE EVALUACIÓN DEL MODELO)
## SENSIBILIDAD --- VERD.POSIT/TOTAL POSITIVO Y ESPECIFICIDAD --- VERD.NEG/TOTAL NEGATIVO
### ACCURACY -- VP +VN/ TOTAL
## HAY QUE TENER EN CUENTA LA NATURALEZA DE LA VARIABLE DICOTÓMICA:
## YA QUE EN ALGUNOS CASOS NOS INTERESA QUE EL PORCENTAJE DE LA SENSIBILIDAD 
## O DE LA ESPECIFICIDAD SEA MAYOR Y GENERALMENTE UN BUEN MODELO TIENE 
## ACCURACY > 0.8. EN NUESTRO CASO DEBEMOS CENTRARNOS EN EL COSTO DE LOS 
## FALSOS POSITIVOS O NEGATIVOS ?? 
## COMO NOS IMPORTA PREDECIR QUE UN CLIENTE SE SUSCRIBA: UN CLIENTE 
## QUE SE HA SUSCRITO Y HEMOS PREDICHO QUE NO(FALSO NEGATIVO); TIENE MENOR COSTO RESPECTO
## RESPECTO A UN CLIENTE QUE NO SE HA SUSCRITO Y HEMOS DICHO QUE SI (FALSO POSITIVO)
## ES DECIR NOS DEBEMOS CENTRAR EN LA SENSIBILIDAD
## PERO SI FUERA POR EJEMPLO LA VARIABLE FRAUDE PUES ESCOGERÍAMOS FALSO NEGATIVO
## (ESPECIFICIDAD)


## CÁLCULO DEL MODELO
library(stargazer)
stargazer(reglog,type="text")

## MATRIZ DE CONFUSIÓN PARA LA EVALUACIÓN DEL MODELO
library(caret)
valores_predichos <- as.numeric(reglog$fitted.values>0.2)
valores_predichos <- factor(valores_predichos, labels = levels(data$y))

caret::confusionMatrix(valores_predichos, data$y, positive = "yes")
table(data$y)
